// src/components/counter.tsx
import { useStore } from "@nanostores/react";
import { counterStore } from "../stores/counterStore";

export const ReactCounter = () => {
    const counter = useStore(counterStore)

    return (
        <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center' }}>
            <button onClick={() => counterStore.set(counterStore.get() - 1)}>Decremnt</button>
            {counter}
            <button onClick={() => counterStore.set(counterStore.get() + 1)}>Increment</button>
        </div>
    )
}

// src/components/counter.vue
<script setup>
import { useStore } from '@nanostores/vue'
import { counterStore } from '../stores/counterStore'

const count = useStore(counterStore)
</script>

<template>
  <div style="display: flex; flex-direction: column; align-items: center;">
    <button @click="counterStore.set(counterStore.get() - 1)">decrement</button>
    {{ count }}
    <button @click="counterStore.set(counterStore.get() + 1)">increment</button>
  </div>
</template>
